config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  # devise_for :users

  devise_for :users,
             controllers: {
                sessions: 'users/sessions',
                registrations: 'users/registrations'
             }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'users#index'

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:create, :destroy]
      resources :likes, only: [:create, :destroy]
    end
  end

  namespace :api do
    resources :users, only: [:id] do
      resources :posts, only: [:index] do
        resources :comments, only: [:index, :create]
      end
    end
  end

  # get '/users', to: 'users#index'
  # get '/users/:id', to: 'users#show', as: 'user'
  # get '/users/:user_id/posts', to: 'posts#index', as: 'user_posts'
  # get '/users/:user_id/posts/:id', to: 'posts#show', as: 'user_post'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, :jwt_authenticatable,
         jwt_revocation_strategy: JwtDenylist
  has_many :posts, foreign_key: :author_id
  has_many :likes, foreign_key: :author_id
  has_many :comments, foreign_key: :author_id
  scope :last_three_posts, ->(user) { Post.where(author: user).last(3) }
  validates :name, presence: true
  validates :posts_counter, comparison: { greater_than_or_equal_to: 0 }

  after_initialize :set_defaults

  def last_three_posts
    posts.last(3)
  end

  private

  def set_defaults
    self.posts_counter ||= 0
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  respond_to :json

  private

  def respond_with(resource, _opts = {})
    resource.persisted? ? register_success : register_failed
  end

  def register_success
    render json: { message: 'Signed up.' }
  end

  def register_failed
    render json: { message: 'Signed up failure.' }
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  respond_to :json

  private

  def respond_with(_resource, _opts = {})
    render json: { message: 'Missing auth token.' }, status: :ok
  end

  def respond_to_on_destroy
    current_user ? log_out_success : log_out_failure
  end

  def log_out_success
    render json: { message: 'Logged out.' }, status: :ok
  end

  def log_out_failure
    render json: { message: 'Logged out failure.' }, status: :unauthorized
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @last_posts = User.last_three_posts @user
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def users_index?
    current_page?(users_path) || current_page?(root_path)
  end
end

app/views/users/_user.html.erb
<div class="users-list-row">
  <div class="users-photo">
    <img src=<%= user.photo || 'https://via.placeholder.com/150' %> alt=<%= "user-#{user.id}" %>>
  </div>
  <div class="users-description-wrapper">
    <a
      <% if users_index? %>
        href=<%= user_path(user) %>
      <% end %>
      class="users-description-content"
    >
      <% if users_index? %>
        <h2><%= user.name %></h2>
      <% else %>
        <h1><%= user.name %></h1>
      <% end %>
      <p>Number of posts: <%= user.posts_counter.nil? ? 0 : user.posts_counter %></p>
    </a>
  </div>
</div>

app/views/users/index.html.erb
<section>
  <div class="users-list">
    <%= render @users %>
  </div>
  <div style="text-align: center; padding-bottom: 24px">
    <% unless current_user.nil? %>
     <%= link_to 'Create new post', new_user_post_path(current_user), class: 'button' %>
    <% end %>
  </div>
</section>

app/views/users/show.html.erb
<section>
  <div class="users-list">
    <%= render @user %>
  </div>
  <div style="padding: 0 24px">
    <div class="user-bio">
      <h2>Bio</h2>
      <p><%= @user.bio %></p>
    </div>
  </div>
  <div class="users-posts">
    <%= render partial: 'posts/post', collection: @last_posts %>
  </div>
  <div style="text-align: center; padding-bottom: 24px">
    <%= link_to 'See all posts', user_posts_path(@user), class: 'button' %>
  </div>
</section>