config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  # devise_for :users

  devise_for :users,
             controllers: {
                sessions: 'users/sessions',
                registrations: 'users/registrations'
             }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'users#index'

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:create, :destroy]
      resources :likes, only: [:create, :destroy]
    end
  end

  namespace :api do
    resources :users, only: [:id] do
      resources :posts, only: [:index] do
        resources :comments, only: [:index, :create]
      end
    end
  end

  # get '/users', to: 'users#index'
  # get '/users/:id', to: 'users#show', as: 'user'
  # get '/users/:user_id/posts', to: 'posts#index', as: 'user_posts'
  # get '/users/:user_id/posts/:id', to: 'posts#show', as: 'user_post'
end

app/models/post.rb
class Post < ApplicationRecord
  after_save :update_posts_counter
  after_destroy :update_posts_counter
  belongs_to :author, class_name: 'User'
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  scope :update_posts_counter, ->(user, count) { user.update(posts_counter: count) }
  # scope :last_five_comments, ->(post) { Comment.where(post:).last(5) }
  validates :title, presence: true
  validates :title, length: { maximum: 250 }
  validates :comments_counter, comparison: { greater_than_or_equal_to: 0 }
  validates :likes_counter, comparison: { greater_than_or_equal_to: 0 }

  def last_five_comments
    comments.last(5)
  end

  def update_posts_counter
    author.update(posts_counter: author.posts.count)
  end
end

app/controllers/api/posts_controller.rb
class Api::PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    user = User.includes(:posts, posts: :comments).find(params[:user_id])
    posts = user.posts

    render json: posts
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.includes(:posts, posts: :comments).find(params[:user_id])
    @posts = @user.posts
  end

  def show
    @post = User.find(params[:user_id]).posts.find(params[:id])
    @like = Like.find_by(author: current_user, post: @post)
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(**post_params, comments_counter: 0, likes_counter: 0)

    respond_to do |format|
      if @post.save
        format.html { redirect_to user_post_path(current_user, @post), notice: 'Post was successfully created.' }
      else
        flash.now[:notice] = 'Something went wrong.'
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    Post.find(params[:id]).destroy

    respond_to do |format|
      format.html { redirect_to user_posts_path(params[:user_id]), notice: 'Post was successfully deleted.' }
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comment_form.html.erb
<%= form_with(model: comment, url: user_post_comments_path(post_id: @post)) do |form| %>
  <% if comment.errors.any? %>
    <div>
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :text, style: "display: block" %>
    <%= form.text_field :text, required: true %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_comments.html.erb
<div class="comments-list">
  <% if comments.empty? %>
    <div class="comment">
      <p>There are no comments yet</p>
    </div>
  <% else %>
    <% comments.each do |comment| %>
      <div class="comment">
        <strong><%= comment.author.name %>:</strong>
        <p><%= comment.text %></p>
        <% if can? :delete, comment %>
          <%= button_to 'Delete comment', user_post_comment_path(comment.author, comment.post, comment), method: :delete %>
        <% end %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/posts/_form.html.erb
<%= form_with(model: post, url: user_posts_path) do |form| %>
  <% if post.errors.any? %>
    <div>
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title, required: true %>
  </div>

  <div>
    <%= form.label :text, style: "display: block" %>
    <%= form.text_field :text, required: true %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="posts-list-post">
  <h3><%= post.title %></h3>
  <p><%= post.text %></p>
  <div style="text-align: end">
    <small>
      Comments: <%= post.comments_counter.nil? ? 0 : post.comments_counter %>,
      Likes: <%= post.likes_counter.nil? ? 0 : post.likes_counter %>
    </small>
  </div>
</div>

app/views/posts/index.html.erb
<section>
  <div class="users-list">
    <%= render @user %>
  </div>
  <div class="users-posts">
    <% @posts.each do |post| %>
      <a href=<%= user_post_path(@user, post) %> class="post">
        <%= render post %>
        <%= render partial: 'comments', object: post.last_five_comments %>
      </a>
    <% end %>
  </div>
</section>

app/views/posts/new.html.erb
<section>
  <% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% end %>

  <h1>Create a new post</h1>
  <%= render 'form', post: @post %>
</section>

app/views/posts/show.html.erb
<section>
  <% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% end %>
  <div class="posts-list-post post-details">
    <div class="post-header">
      <h1><%= @post.title %><span>by <%= @post.author.name %></span></h1>
      <p>
          Comments: <%= @post.comments_counter.nil? ? 0 : @post.comments_counter %>,
          Likes: <%= @post.likes_counter.nil? ? 0 : @post.likes_counter %>
      </p>
    </div>  
    <p class="post-body">
      <%= @post.text %>
    </p>
    <div>
      <% if user_signed_in? %>
        <% if @like %>
          <%= button_to 'Dislike', user_post_like_path(@like.author, @like.post, @like), method: :delete %>
        <% else %>
          <%= button_to 'Like', user_post_likes_path(@post.author, @post) %>
        <% end %>
      <% end %>
    </div>
  </div>
  <%= render partial: 'comments', object: @post.comments %>
  <%= render('comment_form', comment: Comment.new) if user_signed_in? %>
  <% if can? :delete, @post %>
    <%= button_to 'Delete Post', user_post_path(@post.author, @post), method: :delete %>
  <% end %>
</section>